import Head from 'next/head'
import { useTheme } from '@mui/material/styles';

export default function Home({ user }: any) {
  const theme = useTheme();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          oi
        </div>
      </main>
    </>
  )
}
