import Head from 'next/head'
import { Inter } from '@next/font/google'
import { useTheme } from '@mui/material/styles';
import styles from '../styles/index.module.scss';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const theme = useTheme();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          oi
        </div>
      </main>
    </>
  )
}
